### ISSUE TITLE
Update to Font Awesome 4.5.0

### ISSUE THREAD

**Issue by mrcycling** [fontello/fontello#463] opened 2016-01-16 06:48 UTC
Would be nice to have Font Awesome 4.5.0 available so we could have access to the new Google and GooglePlus icons (or any other icon set that offers the updated versions of these logos)

**Comment by danielelder** [comment] 2016-01-18 10:54
+1

I know a temporary solution has been given on issue #457, but updating to the 4.5.0 version would be great.

**Comment by morgmj** [comment] 2016-02-29 22:10
+1

**Comment by puzrin** [comment] 2016-03-02 12:32
Dupe of #457

**Closed by puzrin** 2016-03-02 12:32 UTC
