### ISSUE TITLE
ttfautohint in Windows XP - icons disappear

### ISSUE THREAD

**Issue by srgmatin** [fontello/fontello#464] opened 2016-01-30 23:35 UTC
The icons disappear when I change or enable/disable any CSS properties in Chrome DevTools. It happens in Win XP only. What could it be?

**Comment by vykulakov** [comment] 2016-03-25 13:40
Hi!

I have the same problem on Windows XP in Firefox, Chrome, Opera and Yandex.Browser (it's based on Chromium).

I had created a virtual machine in the VirtualBox and then I had installed the last versions of these browsers. Then I had created the simple HTML page with jQuery, Bootstrap and custom Fontello font (from SVG source). When I open that page in the browsers, icons sometimes disappear. If I 
repeatedly press Ctrl+F5 in the browsers, icons sometimes disappear and then appear. But Bootstrap Glyphicons are displayed always!

What can I do to solve this problem?

P. S. Demo page also works wrong.

**Comment by vykulakov** [comment] 2016-03-25 14:01
I had got problem on four different real PC and on one virtual PC. Bootstrap Glyphicons always work properly.

**Comment by puzrin** [comment] 2016-03-25 14:01
Could you help to create a minimal demo with instructions? Desired:

1. Font with one simple glyph (zip from fontello), if possible.
2. Link to virtual machine (i guess, from MS site), where this bug can be reproduced.

If you have a time - try to resave font via fontforge or any other font editor, and dump via `ttx` utility from `fonttools` package to see difference (if resave provides forking font).

One more notice - disable hinting in fontello setting, to make sure that's not ttfautohint bug.

**Comment by puzrin** [comment] 2016-03-25 14:04
Edited title - problem is specific to XP, not to Chrome only.

**Comment by vykulakov** [comment] 2016-03-25 16:11
Okay....

I downloaded and started the virtual machine "IE8 on XP" for VirtualBox from this url: https://dev.windows.com/en-us/microsoft-edge/tools/vms/windows/.

Then I created font `fontello-1d1dbd1b` with only one symbol and `fontello-bc676347` with four symbols (for my project). Then I simplify my project and put all files into [fontello_bag.zip](https://github.com/fontello/fontello/files/189688/fontello_bag.zip).

So you must copy the archive to VM and open `custom.html` in IE or Firefox (you must download it before). Press repeatedly Ctrl+F5 until the icons will have disappeared.

Example of issue is on ![screenshot](https://cloud.githubusercontent.com/assets/15159594/14047908/dd958ddc-f2bb-11e5-97c5-682df769c612.png).

**Comment by vykulakov** [comment] 2016-03-25 16:36
Sorry, I forgot to disable hinting. When I disabled it, the problem disappeared.

**Comment by puzrin** [comment] 2016-03-25 16:41
> Sorry, I forgot to disable hinting. When I disabled it, the problem disappeared.

Thanks a lot for info! I'll try to rebuild a new version.

**Comment by puzrin** [comment] 2016-03-25 17:34
http://www.freetype.org/ttfautohint/

Could you try to apply ttfautohint 1.5 manually?

- build font without hinting
- apply ttfautohint https://github.com/fontello/fontello/blob/master/internal/fontello/font_build/_lib/worker.js#L152-L155
- leave TTF file only (delete another formats)

Does 1.5 version help?

**Comment by vykulakov** [comment] 2016-03-25 18:51
I can try it only after weekend. Sorry.

**Comment by vykulakov** [comment] 2016-03-25 19:59
Okay.

1. I took the last build without hinting (`fontello_without_hint.ttf` - 2.1kB).
2. I applied ttfautohint: `ttfautohint --no-info --windows-compatibility --symbol fontello_without_hint.ttf  fontello_with_manual_hint.ttf `
3. I got the font with hinting (`fontello_with_manual_hint.ttf` - 5.6kB).
4. I specified new font in my CSS and removed other font types.

...and the problem came back.

**Comment by puzrin** [comment] 2016-03-25 20:12
@vykulakov thanks for info.

Reported to Werner Lemberg (developper of ttfautohint).

**Comment by vykulakov** [comment] 2016-03-25 20:19
Thank you for the wonderful service!

**Comment by lemzwerg** [comment] 2016-03-27 07:04
Where can I download `fontello_without_hint.ttf`?

**Comment by puzrin** [comment] 2016-03-27 07:24
@lemzwerg `settings menu` -> `advanced font settings` -> `hinting` checkbox. It defines should `ttfautohint` be applied or not.

Then select some icons & download. If more help needed - let me know.

**Comment by vykulakov** [comment] 2016-03-27 17:36
> Where can I download fontello_without_hint.ttf?

You can find it in the archive [fonts.zip](https://github.com/fontello/fontello/files/191020/fonts.zip).

**Comment by lemzwerg** [comment] 2016-03-28 05:53
The problem is a bug in ttfautohint – thanks for the report :-)

A quick fix is to add `-f latn` to the ttfautohint command line arguments.

**Comment by puzrin** [comment] 2016-03-28 11:45
@vykulakov could you check? Updated fontello code.

**Comment by vykulakov** [comment] 2016-03-28 13:42
I can not reproduce the problem with your changes -  the problem disappeared. I will try to use new font in my project.

**Comment by puzrin** [comment] 2016-03-30 11:21
@vykulakov can we close this issue?

**Comment by vykulakov** [comment] 2016-03-30 14:36
No, I do not have the button "Close Issue".

**Comment by puzrin** [comment] 2016-03-30 14:52
Close as solved

**Closed** 2016-03-30 14:52 UTC
Labels: ttfautohint
