### ISSUE TITLE
Adding new icon changes custom hex values

### ISSUE THREAD

**Issue by j4cq** [fontello/fontello#502] opened 2016-06-23 06:24 UTC
Each time a new icon is added to a fontello set, the custom hex values for all of the icons in the set change.

This is a problem because there are times where these custom hex values are used in a project instead of just doing css classes (this case might be when you have to add an icon where it's not possible to update the actual html itself).

Can it please be adjusted so this doesn't happen?

Thanks in advance.

**Comment by puzrin** [comment] 2016-07-04 14:15
Seems dupe of #500, should be fixed now. If problem still exists - let me know.

**Closed by puzrin** 2016-07-04 14:15 UTC
