### ISSUE TITLE
Fontello website is changing mapping of contents

### ISSUE THREAD

**Issue by mkhalidnoor** [fontello/fontello#724] opened 2020-11-16 07:37 UTC
As we noticed fontello changed mapping of contents in classes. For example previously content=”e807” associated to class .si-employee:before and now content=”e807” associated to class .si-time-location:before.

Please guide us how frequently you make changes in fontello libraries and also give us link where you wrote that type of changes? As if you will change core libraries this will affect us a lot.

 
![fontello](https://user-images.githubusercontent.com/8483895/99224616-7a33da00-2808-11eb-96c4-8424689299db.png)

**Comment by puzrin** [comment] 2020-12-03 08:48
Dupe of #724/#725

**Closed by puzrin** 2020-12-03 08:48 UTC
