### ISSUE TITLE
Call for fontello.api.update delayed when using HTTP API

### ISSUE THREAD

**Issue by nartallax** [fontello/fontello#750] opened 2021-08-14 14:10 UTC
When you edit icon set within session, font config is not saved immediately after changes, but instead after some delay (3-4 seconds). If within this time window external server invokes /get API endpoint, old config is returned. Such invocation can be caused by "export font" click (which will call external server, which will start font saving process, which will call the endpoint).  
In short, you can't click icons and immediately click "export font". You have to wait, which is not nice.  

**To Reproduce**
1. Create session (with POST to http://${host}/)
2. Go to web interface of this session ( http://${host}/${sessionId})
3. Add/remove icon to set, and within 3 seconds call /get API endpoint
4. You will get zip archive, which will contain config without latest change

**Expected behavior**
I expected to get most recent config from /get API endpoint.  
At the very least, if immediate update is not viable, "export font" button can be locked within time window between update happened on client and delivered to server.

**OS/Browser**
 - OS: Debian 9
 - Browser: chrome

**Comment by rlidwka** [comment] 2021-08-17 13:48
> You have to wait, which is not nice.

You don't *have* to wait, there is a big red button called "Save session" in the top-right corner.

![image](https://user-images.githubusercontent.com/999113/129736922-b4bbcc0d-58d0-4639-a1b8-f88af09a6a75.png)

Automatic save (with 3-second debounce) is a fallback option in case your computer crashes or something. If you want to make sure the session is saved, please do so manually.

*closing as "not a bug"*

**Comment by nartallax** [comment] 2021-08-17 15:26
Did not realise you can get "Save session" button.  
I'm talking about the case when you pass custom URL on session creation. That way, the button is namd "Export font"; when you press it, the font is not saved on Fontello server before redirecting user to this custom URL, that's the problem.  
I use this redirect to call my backend; my backend calls Fontello server for /get endpoint and put the font files where they need to go. Then my backend responds with HTTP 302, getting user back to the Fontello frontend with the session.  
Am I doing this wrong? Should I somehow "listen" to "Save session" button to do things on my custom backend (and how, if so)?

**Comment by puzrin** [comment] 2021-08-17 17:36
Do you use `http` or `https`? Only `https` is supported

**Comment by nartallax** [comment] 2021-08-17 17:56
I use http.  
I guess it's kinda irrelevant (or is it?) as I don't use fontello.com; I cloned the repository and lauch the Fontello locally.

**Comment by rlidwka** [comment] 2021-08-17 18:40
> That way, the button is namd "Export font"; when you press it, the font is not saved on Fontello server before redirecting user to this custom URL

According to the code, it saves, then it redirects:
https://github.com/fontello/fontello/blob/bc1c49affccb819b2fb5d30a3fb89b512e40e2a9/client/fontello/blocks/toolbar/toolbar.js#L125-L132

gonna check it again tomorrow, maybe there's a race condition there, and it saves old config somehow?

**Comment by nartallax** [comment] 2021-08-17 19:00
Debugged it a little. Looks like the problem is here:

https://github.com/fontello/fontello/blob/bc1c49affccb819b2fb5d30a3fb89b512e40e2a9/client/fontello/blocks/toolbar/toolbar.js#L94-L98

The first save just don't happen on page open, so it is ignored on button press.  
That also means that if you open page, then trigger autosave (by selecting/deselecting icon and waiting), it will save on button properly.

**Closed** 2021-08-20 15:40 UTC

**Comment by rlidwka** [comment] 2021-08-20 15:54
Thanks for debugging, that code branch is now removed.
 
I think it was necessary back in 2013, but not anymore.
