### ISSUE TITLE
Codes get rewritten when adding new glyphs

### ISSUE THREAD

**Issue by jacobmattsson** [fontello/fontello#725] opened 2020-11-18 09:45 UTC
**Description**
We have been using Fontello to generate of font icons for a year or so now, and it has been working great! But now, we have run into some problems where codes of the existing glyphs get overwritten when we add new glyphs.

This problem is probably the same as has been reported in #724, but I create a new bug report just in case it isn't.

**To Reproduce**
Here is an example:

- I have 100 glyphs in my JSON config. 
- I upload the config to fontello.com (using a MAKE script) and look at the details of one of the glyphs, the 'check' glyph. It has code E864:
![screenshot](https://user-images.githubusercontent.com/270561/99513271-ba22ca80-298a-11eb-8d67-1ccd8c082443.png)
- I then add a new glyph - the 'help' glyph. It gets the code E864:
![screenshot](https://user-images.githubusercontent.com/270561/99513276-bb53f780-298a-11eb-97ea-824bd3902ac3.png) 
- I now again look at the details of the 'check' glyph. I now has the code E830:
![screenshot](https://user-images.githubusercontent.com/270561/99513279-bbec8e00-298a-11eb-8a69-b55a4a2f46e3.png)

**Expected behavior**
I expect that existing glyphs should keep their codes intact, when new glyphs are added.
I expect that new glyphs don't get codes that are used by existing glyphs.

I have not observed this behavior earlier. It since we identify the glyphs/icons in the font by the codes (in some cases), this messes up the font completely.

Why do we experience this behavior now? Have you made a deliberate change that causes this behavior, or is it bug? 

**OS/Browser**
 - Ubuntu 18.04
 - Chrome 86.0.4240.75 (Official Build) (64-bit) and Firefox 82.0.3 (64-bit)

**Font/config**
`config.json` is uploaded with MAKE script (containing only custom icons). However, same problem occurs if I drag the 'config.json into an empty fontello.com.

**Comment by smerriman** [comment] 2020-11-18 23:39
I'm experiencing exactly the same behavior - this is causing the fontello project to be pretty broken at the moment.

**Comment by smerriman** [comment] 2020-11-19 02:13
In fact, I'm experiencing all sorts of weird behaviour. If I import my config.json and check the 'codes' tab, all looks fine. If I then import a second time, all of the codes change to an increasing sequence. Importing a third back, and it's back to normal, etc.

Looks like lots of bugs with the codes - hopefully all of these issues are related and can be fixed as one.

**Comment by rlidwka** [comment] 2020-11-19 13:16
It is a bug, but one I can't reproduce at the moment.

Can you please show a `config.json` file on which this weird behaviour is observed (any will do, the smaller the better)?

Also step-by-step guide how to reproduce it will be helpful, something like this:

1. Press "Reset all changes" button
2. Upload config
3. Select a glyph? Which one, custom or built-in?
4. ...

**Comment by smerriman** [comment] 2020-11-19 20:31
Here's an example of the latter bug I mentioned. 

Reset all changes, then import the following config (renamed from txt to json). Click on 'Customize codes' and see E82B and E814. Then immediately go back to the menu and reimport the same config to see E800 and E801. Repeat again to see if go back to E82B and E814.

[config-test.txt](https://github.com/fontello/fontello/files/5569503/config-test.txt)

It looks like when you have existing 'Custom icons', and import a config file which uses the same codes, they all get wiped. This definitely never used to happen.

**Comment by jacobmattsson** [comment] 2020-11-19 22:16
I think the reason why we are experiencing these problems is that we (for some reason) have "gaps" in the code range in the config.

Have a look at this config:  [my-config.txt](https://github.com/fontello/fontello/files/5569933/my-config.txt)

It has two glyphs, the first one has code 59392/E800 and the second one has code 59392/E802. Notice the gap, i.e. the missing code 59393/E801 in the range (between the lowest and the highest code)!

To reproduce the described problem, do the following:

1. Open a "clean" fontello.com and drag this config (after first having changed the file extension to 'json') into the page. 
2. Make note of the codes (first glyph has code E800 and the second glyph has code E802).
3. Drag this third icon (after first having changed the file extension to 'svg') into the page: ![help.png](https://user-images.githubusercontent.com/270561/99728872-5f888c00-2aba-11eb-9587-d9604f89abda.png)
4. Observe how the second glyph now have changed its code, from E802 to E801, and how the newly added third glyph received code E802. 

I don't know why we have these "gaps" in code range in our config, but that fact seems to be causing these problems.

### Stats from our config
```
Number of glyphs in config: 100

Existing codes
-----------------
593xx:   8
594xx:  86
595xx:   6
-----------------
Total: 100 => OK!

First code: 59392
Last  code: 59505

Missing codes
-------------
59440
59441
59442
59444
59448
59449
59456 - 59463
-------------
In total: 14

Verification
------------
Last code - First code + 1 = 114 (i.e. 14 more than 100) => OK!
```

### Conclusion
```
Rewritten code (i.e. original code of the 'check' glyph being rewritten) : 59492

(Rewritten code - First code) = (59492 - 59392) = 100 
=> 
There are exactly 100 codes (i.e. equal to the number of glyphs in the config) available (but not used in this config) in the range [59392, 59492) == [59392, 59491] 
=>
Rewritten code (59492) is the **first code** that would not have been used if there were no gaps in the code range assigned by the Fontello tool (i.e. if all codes in the range [59392, 59491] were used for the 100 glyphs). 
=>
The Fontello tool seems to expect that there are no gaps the range of codes in the config.
```

**Comment by puzrin** [comment] 2020-11-20 12:10
While this cerataintly looks like a bug, i suggest you also check `settings -> encoding`.

May be "unicode" will be better for your needs. PUA and ASCII force assign first available code fom range on select, even in char has some. The only exclusion is config import after reset - then codes should be preserved always.

**Comment by jacobmattsson** [comment] 2020-11-20 12:56
I forgot to mention - I've already experimented quite a lot with the different encoding options, after having read in other posts that you recommend using `unicode` to preserve glyph codes.

However, using `unicode` make no difference in this case!

If I extend my reproducible steps (from my previous comment) with a step where the encoding is set to `unicode`:
![fontello_code_bug__unicode_encoding_makes_no_difference](https://user-images.githubusercontent.com/270561/99801795-e418f000-2b36-11eb-83ad-c222bc9dac2e.png)
, the result in still the same (the code of the second glyph gets overwritten when a third glyph is added), i.e.:

1. Open a "clean" fontello.com and drag this config (after first having changed the file extension to 'json') into the page.
2. Open settings and set encoding to `unicode`. 
3. Make note of the codes (first glyph has code E800 and the second glyph has code E802).
4. Drag this third icon (after first having changed the file extension to 'svg') into the page: help.png
5. Observe how the second glyph now have changed its code, from E802 to E801, and how the newly added third glyph received code E802.

Furthermore, it makes no difference if I set the encoding _before_ (or after) I drag the config into the page.

So there doesn't seem to be a workaround for this bug ... :-(

Also, while I was experimenting with setting a specific encoding, I noticed that this setting is **not** saved in the config file (after having downloaded it again). That surprised me, since if that setting would have solved this problem, then I would have had to set this setting manually every time I wanted to modify my set of glyphs. Is that working as expected, or have I done something wrong there?

**Comment by rlidwka** [comment] 2020-11-26 15:22
Please, check again if this issue is fixed.

-------

I'm sorry for the delay. I believe this bug is related to #724, and it is (or was) a corner face we've forgot. Couldn't reproduce exactly (uploading `help.svg` causes error?), but similar thing happens with another glyph.

**Comment by jacobmattsson** [comment] 2020-11-27 16:32
I can confirm that this problem now seems to be fixed! I can no longer reproduce it, neither with my example config (above) nor with my real config.

Thanks a lot for the quick response! Great work!

**Comment by grumd** [comment] 2020-11-30 17:10
I can still reproduce a similar issue with my config. I think having custom svg icons triggers it.

Example config.json: https://puu.sh/GSLRw/3afc40d0cf.json

Video: https://puu.sh/GSLRU/9b9b26c3c2.mp4

I import this config.json and see 0021 as the glyph code. I import it again and now I see 0022 as the glyph code. Then back to 0021.

**Comment by grumd** [comment] 2020-11-30 17:25
@rlidwka I probably should have mentioned you, please see the comment above 🙏

**Comment by smerriman** [comment] 2020-12-03 21:30
I am also still experiencing the issue with imports - can still be replicated via my instructions and test file above.

**Comment by rlidwka** [comment] 2020-12-07 11:18
@smerriman should be fixed now (https://github.com/fontello/fontello/commit/a43b2a6ce76295b62b8c3a3d41e7b6e4a4e8d86d), can you please verify?

Everything should be working. Does anyone still see issues related to codes changing?

**Comment by smerriman** [comment] 2020-12-09 01:05
Looking good to me now.

**Closed** 2020-12-09 02:33 UTC

**Comment by matildaaistre** [comment] 2020-12-11 15:13
I'm still having this problem, tried this as late as just now and all my glyph codes still gets rewritten in the export. Is this happening for someone else also?

**Comment by puzrin** [comment] 2020-12-11 16:46
@matildaaistre if you are sure you problem is related to this issue, please provide detailed instruction how to reproduce, as been requested. That's important.
