### ISSUE TITLE
Icon names get a `-1` suffix...

### ISSUE THREAD

**Issue by francoismassart** [fontello/fontello#719] opened 2020-10-19 12:52 UTC
I've been using fontello via [fontello.com](fontello.com) for a while now.

Recently, I noticed the exported `config.json` file did get new names for my custom font icons with a `-1` suffix.
Even for icon with unique name...

If I spend time renaming the icons, the next time I drag and drop my `config.json` on fontello, the names still get the suffix...

Any help ? Thanks!

**Comment by puzrin** [comment] 2020-10-19 12:57
Dupe of #714

**Closed by puzrin** 2020-10-19 12:57 UTC
