### ISSUE TITLE
Fontello crashes iexplorer 8

### ISSUE THREAD

**Issue by TahicheVivo** [fontello/fontello#389] opened 2015-02-03 09:13 UTC
This drove me crazy for days...
I had a site that was working fine, checked in all browsers including iexplorer8,  but kept crashing on the client´s computer. As soon as he (or workmates as they all had the same configuration) opened the page, iExplorer just crashed with a fatal error, some dll unforgiving error... 
It turns out fontello was crashing this specific Windows XP/ IExplorer 8 configuration, (as i said i could never reproduce it on my setup).
It took me days to narrow it down to fontello, as i previously had other icon fonts like font-awesome working fine and i never expected a crash due to a font. Then again, it´s iExplorer... 
Wanted to drop it here in case it saves someone from the headache...

**Comment by puzrin** [comment] 2016-03-09 19:49
Let's close it, since configuration is unclear & not reproduceable. May be latest SP needed and so on. Also, XP is no longer supported.

**Closed by puzrin** 2016-03-09 19:49 UTC
