### ISSUE TITLE
Update font awesome to latest version

### ISSUE THREAD

**Issue by j4cq** [fontello/fontello#499] opened 2016-06-07 03:59 UTC
Firstly - well done on this project, I use it pretty much daily and it's awesome.

Would it be possible to update font awesome to the latest version - there are heaps of new icons, including the new instagram logo.

Thanks!

**Comment by puzrin** [comment] 2016-07-04 14:23
Dupe of #434

**Closed by puzrin** 2016-07-04 14:23 UTC
