### ISSUE TITLE
Font Awesome 4.5.0

### ISSUE THREAD

**Issue by sodbileg** [fontello/fontello#457] opened 2015-12-10 03:59 UTC
Hi. When is Fontello going to be updated with Font Awesome 4.5.0?

**Comment by geekitude** [comment] 2015-12-11 11:15
I second this, it would be really nice :)

**Comment by tikiki** [comment] 2015-12-20 15:30
Yep, I would love it too, I would like to use icons which are not included on Fontello now :p

**Comment by sylvainar** [comment] 2015-12-20 15:40
The same for me ! :)

**Comment by vremy** [comment] 2015-12-21 07:37
For now you can upload the new fontawesome font (svg file) to fontello and use that  :) The disadvantage is that you have to fill in all the character names for the font...

**Comment by sodbileg** [comment] 2016-01-11 09:31
@vremy, Didn't know about that. Thank you so much for the info. The disadvantage wasn't that bad for me, because I just wanted a new Google+ icon. Fontello is great :)

**Comment by puzrin** [comment] 2016-03-02 12:45
Dupe of #434

**Closed by puzrin** 2016-03-02 12:45 UTC
