### ISSUE TITLE
Some FontAwesome fonts missing?

### ISSUE THREAD

**Issue by hardcodet** [fontello/fontello#545] opened 2016-10-20 15:16 UTC
Hi there

Just FYI: I browsed Fontello the first time, and noticed that the search for "ban" ("fa-ban") didn't yield a result despite your update to 4.6.3. I quickly glanced over the list and didn't see it, but might well have missed it in the list (in case it's stored under a different name).

Cheers,
Philipp

**Comment by sebastienbarre** [comment] 2016-10-24 20:18
Unfortunately, yes, it is stored as `block`. That's an issue with Fontello, many of the Font Awesome glyphs are stored with different aliases, which makes searching difficult. I fixed 111 out of 600+ back in August in fontello/awesome-uni.font#8, but there's more work to do. Feel free to create a similar PR.

**Comment by puzrin** [comment] 2016-10-28 00:08
@hardcodet there are no missed glyphs but names are different by historic reasons (because fontello supports multiple fonts, not FA only).

https://github.com/fontello/awesome-uni.font/blob/master/config.yml - anyone can go there and add common aliases.

Closing as "not a bug".

**Closed by puzrin** 2016-10-28 00:08 UTC
